exports.properties = [
  {
    period: 20,
    image: require("../assets/kampala.jpg"),
    location: "Uganda",
    street: "Kampala",
    slag: "kampala",
    investors: 29,
    price: 1100000,
    paid: 800000,
    annual_yield: 30,
    type: 0,
    modification_datetime: new Date(),
    why: "",
  },
  {
    period: 20,
    image: require("../assets/jinja.jpeg"),
    location: "Uganda",
    street: "Jinja",
    slag: "jinja",
    investors: 0,
    price: 0,
    paid: 150000,
    annual_yield: 35,
    type: 1,
    modification_datetime: new Date(),
  },

  {
    period: 20,
    image: require("../assets/mombasa.jpg"),
    location: "Kenya",
    street: "Mombasa",
    slag: "mombasa",
    investors: 0,
    price: 150000,
    paid: 0,
    annual_yield: 35,
    type: 1,
    modification_datetime: new Date(),
  },

  {
    period: 20,
    image: require("../assets/zanzibar.jpg"),
    location: "Zanzibar",
    street: "Zanzibar",
    slag: "zanzibar",
    investors: 0,
    price: 150000,
    paid: 0,
    annual_yield: 35,
    type: 1,
    modification_datetime: new Date(),
  },
];

exports.low_investment = "$150";
